name=uDrive
version=1.0.0
author=circuiTician
maintainer=circuitmaster8@gmail.com
sentence=uDrive library
paragraph=bla bla bla.
category=Others
url=https://www.circuiTician.com
architectures=*
